customhost = "database-1.cryqgq9lp8wy.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "yongxianye-employee"
customregion = "us-east-1"
